// Code generated by MockGen. DO NOT EDIT.
// Source: transaction/event_scope.go
//
// Generated by this command:
//
//	mockgen -source=transaction/event_scope.go -destination=transaction/mocks/mock_event_scope.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockScopeWithDomainEvent is a mock of ScopeWithDomainEvent interface.
type MockScopeWithDomainEvent struct {
	ctrl     *gomock.Controller
	recorder *MockScopeWithDomainEventMockRecorder
	isgomock struct{}
}

// MockScopeWithDomainEventMockRecorder is the mock recorder for MockScopeWithDomainEvent.
type MockScopeWithDomainEventMockRecorder struct {
	mock *MockScopeWithDomainEvent
}

// NewMockScopeWithDomainEvent creates a new mock instance.
func NewMockScopeWithDomainEvent(ctrl *gomock.Controller) *MockScopeWithDomainEvent {
	mock := &MockScopeWithDomainEvent{ctrl: ctrl}
	mock.recorder = &MockScopeWithDomainEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopeWithDomainEvent) EXPECT() *MockScopeWithDomainEventMockRecorder {
	return m.recorder
}

// ExecuteWithPublish mocks base method.
func (m *MockScopeWithDomainEvent) ExecuteWithPublish(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithPublish", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteWithPublish indicates an expected call of ExecuteWithPublish.
func (mr *MockScopeWithDomainEventMockRecorder) ExecuteWithPublish(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithPublish", reflect.TypeOf((*MockScopeWithDomainEvent)(nil).ExecuteWithPublish), ctx, fn)
}
